<?xml version="1.0" encoding="UTF-8"?>

<!--
  **
  ** This file is maintained by amandel (Andreas Mandel),
  ** mgriffel (Michael Griffel) and amessner (Albrecht Messner).
  **
  ** PLEASE do not modify this file without approval from
  ** the maintainers!
  **
  -->
<app:app-info xmlns:app="http://www.jcoderz.org/app-info-v1.0"
         xmlns:xi="http://www.w3.org/2001/XInclude">
   <application
      id="1"
      name="FawkeZ"
      short-name="FWK"
      package="org.jcoderz.commons">

<!-- =============================================
     Runtime Errors
     ============================================= -->
<group
   id="1"
   name="Runtime Error"
   short-name="RTE"
   package="org.jcoderz.commons"
   base-exception="org.jcoderz.commons.BaseRuntimeException">
   <message
      id="1"
      name="INTERNAL_ERROR"
      level="SEVERE"
      base-exception="org.jcoderz.commons.RuntimeErrorException">
      <text>
         The system encountered an unexpected condition, or contains
         a software bug. Details: {TECHNICAL_DESCRIPTION}.
      </text>
      <solution>
         Review the log file to determine the problem that led
         to the error condition.
      </solution>
   </message>

   <message
      id="2"
      name="ARGUMENT_MALFORMED"
      level="WARNING"
      base-exception="org.jcoderz.commons.BaseRuntimeException">
      <text>
         The given argument is at least partly malformed.
         Argument ''{ARGUMENT_NAME}'' cannot be set to
         value ''{Serializable:ARGUMENT_VALUE}''. Detailed description: {HINT}.
      </text>
      <solution>
         Supply a correct value for the argument.
      </solution>
   </message>

   <message
      id="3"
      name="ASSERTION_FAILED"
      level="SEVERE"
      base-exception="org.jcoderz.commons.BaseRuntimeException">
      <text>
         Assertion failed. A condition is tested
         and found to be false. Message: {MESSAGE}.
      </text>
      <solution>
         .
      </solution>
   </message>

   <message
      id="4"
      name="INCONSISTENT_DATABASE"
      level="SEVERE"
      base-exception="org.jcoderz.commons.BaseRuntimeException">
      <text>
         A value read from the database was invalid.
         The database value {Serializable:ARGUMENT_VALUE} of column
         {COLUMN} in table {TABLE} could not be converted into
         the java type {TYPE}. Possibly the database has been
         modified manually, or the software that wrote the database
         contains a bug.
      </text>
      <solution>
         Correct the value in the database if modified manually.
      </solution>
   </message>

   <message
      id="5"
      name="REMOTE_CALL_FAILURE"
      level="SEVERE"
      base-exception="org.jcoderz.commons.RuntimeErrorException">
      <text>
         The call to a internal remote object failed.
      </text>
      <solution>
         Review the log file to determine the problem that led
         to the error condition.
      </solution>
   </message>

   <message
      id="6"
      name="DATABASE_INTEGRITY_ERROR"
      level="SEVERE"
      base-exception="org.jcoderz.commons.InconsistentDatabaseException">
      <text>
         While accessing table {TABLE}, the following problem was
         encountered: {PROBLEM}.
      </text>
      <solution>
         Review the log file to determine the problem that led
         to the error condition.
      </solution>
   </message>

   <message
      id="7"
      name="DATABASE_ACCESS_FAILED"
      level="SEVERE"
      base-exception="org.jcoderz.commons.RuntimeErrorException">
      <text>
         The system encountered an exception while accessing a database.
      </text>
      <solution>
         Review the log file to determine the problem that led
         to the error condition.
      </solution>
   </message>
   <message
      id="8"
      name="ARGUMENT_MAX_LENGTH_VIOLATION"
      level="WARNING"
      base-exception="org.jcoderz.commons.ArgumentMalformedException">
      <text>
         The given argument is at least partly malformed.
         Argument ''{ARGUMENT_NAME}'' cannot be set to
         value ''{Serializable:ARGUMENT_VALUE}''. The length of the Value
         ({Integer:ARGUMENT_LENGTH}) exceeds the allowed maximum length
         ({Integer:MAX_LENGTH}) for {Class:ARGUMENT_CLASS}.
      </text>
      <solution>
         Supply a correct value for the argument.
      </solution>
   </message>
   <message
      id="9"
      name="ARGUMENT_MIN_LENGTH_VIOLATION"
      level="WARNING"
      base-exception="org.jcoderz.commons.ArgumentMalformedException">
      <text>
         The given argument is at least partly malformed.
         Argument ''{ARGUMENT_NAME}'' cannot be set to
         value ''{Serializable:ARGUMENT_VALUE}''. The length of the Value
         ({Integer:ARGUMENT_LENGTH}) is below the allowed minimum length
         ({Integer:MIN_LENGTH}) for {Class:ARGUMENT_CLASS}.
      </text>
      <solution>
         Supply a correct value for the argument.
      </solution>
   </message>
   <message
      id="10"
      name="ARGUMENT_MAX_VALUE_VIOLATION"
      level="WARNING"
      base-exception="org.jcoderz.commons.ArgumentMalformedException">
      <text>
         The given argument is at least partly malformed.
         Argument ''{ARGUMENT_NAME}'' cannot be set to
         value ''{Serializable:ARGUMENT_VALUE}''. The value
         exceeds the allowed maximum ({Number:MAX_VALUE})
         for {Class:ARGUMENT_CLASS}.
      </text>
      <solution>
         Supply a correct value for the argument.
      </solution>
   </message>
   <message
      id="11"
      name="ARGUMENT_MIN_VALUE_VIOLATION"
      level="WARNING"
      base-exception="org.jcoderz.commons.ArgumentMalformedException">
      <text>
         The given argument is at least partly malformed.
         Argument ''{ARGUMENT_NAME}'' cannot be set to
         value ''{Serializable:ARGUMENT_VALUE}''. The value
         is below {Number:MIN_VALUE}, the allowed minimum
         for {Class:ARGUMENT_CLASS}.
      </text>
      <solution>
         Supply a correct value for the argument.
      </solution>
   </message>
   <message
      id="12"
      name="ARGUMENT_PATTERN_VIOLATION"
      level="WARNING"
      base-exception="org.jcoderz.commons.ArgumentMalformedException">
      <text>
         The given argument is at least partly malformed.
         Argument ''{ARGUMENT_NAME}'' cannot be set to
         value ''{Serializable:ARGUMENT_VALUE}''. The value
         does not match the restrictive pattern
         ''{String:PATTERN}'' for {Class:ARGUMENT_CLASS}.
      </text>
      <solution>
         Supply a correct value for the argument.
      </solution>
   </message>
   <message
      id="13"
      name="ARGUMENT_FRACTION_DIGITS_VIOLATION"
      level="WARNING"
      base-exception="org.jcoderz.commons.ArgumentMalformedException">
      <text>
         The given argument is at least partly malformed.
         Argument ''{ARGUMENT_NAME}'' cannot be set to
         value ''{Serializable:ARGUMENT_VALUE}''. The value
         has {Number:ARGUMENT_FRACTION_DIGITS} fraction digits and
         exceeds the allowed maximum {Number:MAX_FRACTION_DIGITS}
         for {Class:ARGUMENT_CLASS}.
      </text>
      <solution>
         Supply a correct value for the argument.
      </solution>
   </message>
   <message
      id="14"
      name="UNEXPECTED_EXCEPTION"
      level="SEVERE"
      base-exception="org.jcoderz.commons.BaseRuntimeException">
      <text>
         An exeption occured that was not expected in the current
         code.
      </text>
      <solution>
         .
      </solution>
   </message>
   <message
      id="15"
      name="EXCEPTION_CREATED"
      level="FINE">
      <text>
        An Exception with symbol {SYMBOL} has been created.
        Exception Message is: {MESSAGE}
      </text>
      <solution>
        This fact is just written for the records here for the records. There is
        normally no action needed. This is just for debugging purposes.
      </solution>
   </message>
   <message
      id="16"
      name="RUNTIME_EXCEPTION_CREATED"
      level="FINE">
      <text>
        An RuntimeException with symbol {SYMBOL} has been created.
        Exception Message is: {MESSAGE}
      </text>
      <solution>
        This fact is just written for the records here for the records. There is
        normally no action needed. This is just for debugging purposes.
      </solution>
   </message>
</group>
<!-- =============================================
     Common Messages
     ============================================= -->
<group
   id="2"
   name="Common Error"
   short-name="CMN"
   package="org.jcoderz.commons">
   <message
      id="1"
      name="ENTITY_NOT_FOUND"
      level="SEVERE"
      base-exception="org.jcoderz.commons.BaseException">
      <text>
         A database entry in table {TABLE} was not found.
         No rows were returned when executing the
         finder method ''{FINDER}'' with the argument(s)
         ''{Serializable:ARGUMENTS}'' on entity bean {ENTITY}.
      </text>
      <solution>
         Review the log file to determine if the usage of the
         Administration Tool led to the error. Create the requested value
         prior to using the Administration Tool or change the query used for
         retrieving the value via the Adminstration Tool.
      </solution>
   </message>
</group>

   </application>
</app:app-info>
